### PR TITLE
Bumping cosmos sdk version to 4.39.0

### PR DESCRIPTION
**Pull request by simplynaveen20**
Bumping cosmos sdk  version to 4.39.0

### CODE REVIEW

**Comment by RaviTella** [comment]
AzureCosmosClient.java has a comment at the top showing the version of the SDK. It was already outdated. I might have missed changing it. Either update it or remove it. All else looks good.

**Comment by simplynaveen20** [comment]
> AzureCosmosClient.java has a comment at the top showing the version of the SDK. It was already outdated. I might have missed changing it. Either update it or remove it. All else looks good.

Done, removed the version number to V4

**Comment by RaviTella** [comment]
> > AzureCosmosClient.java has a comment at the top showing the version of the SDK. It was already outdated. I might have missed changing it. Either update it or remove it. All else looks good.
> 
> Done, removed the version number to V4

All good!

**Review by RaviTella — APPROVED** [review]
Looks good!

**Pull request merged**
